Initial SDMX 3.0 XML schemas and supporting Section 3A documentation
sdmx-twg/sdmx-ml pull request #21
Opened 2021-03-02 11:16 UTC by sdmx3mdt

Changes
* Modifications to the SDMX 2.1 XML schemas to bring them up to the SDMX 3.0 specification
* Addition of the SDMXStructureStructureMappings.xsd schema file for the new SDMX 3.0 mapping structures
* Deletion of XSD files for XML documents obsolete in SDMX 3.0 e.g. SOAP Query request documents
* SDMX 3.0 versions of the Section 3A supporting documentation Parts I to V
* SDMX 3.0 version of the introductory Section 3A SDMX_3-0-0_SECTION_3A_SDMX_ML

To Do
* Samples
* Section 3A Part VI samples explanatory text

2021-03-12 18:50 UTC, dosse commented
@sdmx3mdt Before committing 3.0 files into develop, the develop branch with the SDMX 2.1 files needs:
- its welcome readme page to be improved to clarify what the repo contains.  I did that and made a pull request: https://github.com/sdmx-twg/sdmx-ml/pull/22 Would you be able to merge this please into develop?
- to be merged into master. Once this is done I propose the folk master to keep a trace and easy entry point to the 2.1 files.

Please let me know if I understood wrongly, or if you have no rights to commit my request.

2021-03-14 23:19 UTC, dosse commented
The AttributeType misses the MeasureRelationship and the AttributeRelationshipType that defines the relationship between an attribute and other data structure definition components still currently wrongly states: `(None | (Dimension+, AttachmentGroup*) | Group | PrimaryMeasure)`

I believe that we agreed to:
- Deprecate the PrimaryMeasure
- Attributes may follow one or more Measures using a MeasureRelationship that is a similar mechanism to the AttributeRelationship with Dimensions
- The AttributeRelationship options now are (only): None, Dimension(s), Group, Observation
- The AttachmentGroup was removed for simplification

The AttributeRelationshipType should thus be: ( ( None | Dimension+ | Group | Observation ), Measure* )

For more info see: https://metadatatechnology.com/sdmx3/designs/003/revisions/003%20Microdata%20Exchange%20-%20Design%20v1.3.0%20-%20with%20comments%20log%2012Feb21.docx

2021-03-15 13:16 UTC, sdmx3mdt commented
@dosse I have no commit rights -however it looks like Xavier approved, and you have already done it.
However,  I re-drafted the sdmx-ml readme in the pull request #21 to align it with those for the sdmx-json and sdmx-csv repos. Merging pull request #21 will therefore overwrite the readme you have created.

2021-03-15 14:16 UTC, sdmx3mdt commented
@dosse concerning AttributeType...
Are you looking at the right version of the schema?
The latest at the head of sdmx3mdt:develop and the version in the pull request seems have what you expect.
The attached screenshot is what I can see:

![Attribute](https://user-images.githubusercontent.com/79863147/111167243-d16c7000-8598-11eb-89c1-f19f8a123aeb.PNG)

2021-03-15 17:25 UTC, dosse commented
@sdmx3mdt In the structure document (SDMX_3-0-0_SECTION_3A_PART_III_STRUCTURE.doc), shouldn't isMultiLingual have as default "false"?

2021-03-25 18:05 UTC, dosse requested changes
Hello @jgager and @glennmdt, please see the issues I found so far in the code that should be addressed. It also includes the issues mentioned in the email exchange:
- remove/change MetadataStructureComponents and ReportStructure in MetadataStructureDefinition to an "AttributeList"
- remove link to MSD in MetadataSet
- rename Att to Attribute in MetadataSet

Thanks a lot in advance.

2021-03-25 18:05 UTC, dosse commented on schemas/SDMXMetadataGeneric.xsd
> +						</xs:element>
The MetadataSet cannot reference the MetadataStructure (because that doesn't contain the allowable targets anymore). At least this is what I understand from https://metadatatechnology.com/sdmx3/designs/001/baseline/001%20Reference%20Metadata%20V3.0.2%20-%20with%20comments%20log.docx.
Could you please clarify? If confirmed then these lines need to be deleted.

2021-03-25 18:05 UTC, dosse commented on schemas/SDMXMetadataGeneric.xsd
> +	<xs:element name="Att" type="AttributeType">
I think "Attr" or "Attribute" would be easier understandable.

2021-03-25 18:05 UTC, dosse commented on schemas/SDMXStructureMetadataStructure.xsd
> +					<xs:element ref="ReportStructure"/>
The ReportStructure should be removed. Matt's documents said: "_The Metadata Attributes are now a direct child of the MSD and not children of Report Structure containers._" If you need a componentlisttype, to align with approach for adding components to dsd, then this should be called "AttributeList" or "MetadataAttributeList".

2021-03-25 18:05 UTC, dosse commented on schemas/SDMXCommon.xsd
> +				<xs:attribute name="version" type="VersionType" use="optional" default="1.0">
If the version is not specified then the artefact is now non-versioned, rather than having version "1.0". The default should be removed.

2021-03-25 18:05 UTC, dosse commented on schemas/SDMXCommon.xsd
> +						<xs:documentation>This version attribute holds a version number in the format of #[.#]+ (see common:VersionType definition for details). If not supplied, the version number is defaulted to 1.0.
Same comment as above.

2021-03-25 18:05 UTC, dosse commented on schemas/SDMXCommonReferences.xsd
> +			<xs:pattern value="(0|[1-9]\d*)(\.(0|[1-9]\d*)){2}(\-(([A-Za-z\-]|([A-Za-z\-][A-Za-z0-9\-]+)|([A-Za-z0-9\-]+[A-Za-z\-][A-Za-z0-9\-]*))|(0|[1-9][0-9]*))(\.(([A-Za-z\-]|([A-Za-z\-][A-Za-z0-9\-]+)|([
This regex seems very, very long. The (second) one mentioned in the feature document seems much shorter. To be checked.

2021-03-25 18:05 UTC, dosse commented on schemas/SDMXStructureOrganisation.xsd
> -				</xs:sequence>
The semantic versioning feature document states: "_The OrganisationScheme artefacts will not use a version number anymore._" The version should be removed from this type.

2021-03-25 18:05 UTC, dosse commented on schemas/SDMXStructureOrganisation.xsd
> -				<xs:attribute name="isFinal" type="xs:boolean" use="optional" fixed="false"/>
In documentation replace "_is always provided a fixed identifier and version, and is never final_" with "_is always provided a fixed identifier and is never versioned_". Restrict the usage of the "version" attribute.

2021-03-25 18:05 UTC, dosse commented on schemas/SDMXStructureOrganisation.xsd
> -				<xs:attribute name="isFinal" type="xs:boolean" use="optional" fixed="false"/>
In documentation replace "_is always provided a fixed identifier and version, and is never final_" with "_is always provided a fixed identifier and is never versioned_". Restrict the usage of the "version" attribute.

2021-03-25 18:05 UTC, dosse commented on schemas/SDMXStructureOrganisation.xsd
> -				<xs:attribute name="isFinal" type="xs:boolean" use="optional" fixed="false"/>
In documentation replace "_is always provided a fixed identifier and version, and is never final_" with "_is always provided a fixed identifier and is never versioned_". Restrict the usage of the "version" attribute.

2021-03-25 18:05 UTC, dosse commented on schemas/SDMXStructureOrganisation.xsd
> +				<xs:attribute name="version" type="common:VersionType" use="optional" fixed="1.0"/>
In documentation replace "_is always provided a fixed identifier and version, and is never final_" with "_is always provided a fixed identifier and is never versioned_". Restrict the usage of the "version" attribute.

2021-03-25 18:15 UTC, jgager commented
> Hello @jgager and @glennmdt, please see the issues I found so far in the code that should be addressed. It also includes the issues mentioned in the email exchange:
> 
> * remove/change MetadataStructureComponents and ReportStructure in MetadataStructureDefinition to an "AttributeList"
> * remove link to MSD in MetadataSet
> * rename Att to Attribute in MetadataSet
> 
> Thanks a lot in advance.

@dosse FYI, we can change ReportStructure to AttributeList, but cannot remove MetadataStructureComponents as it is necessary for the type refinement.

2021-03-25 21:31 UTC, dosse commented
> > Hello @jgager and @glennmdt, please see the issues I found so far in the code that should be addressed. It also includes the issues mentioned in the email exchange:
> > 
> > * remove/change MetadataStructureComponents and ReportStructure in MetadataStructureDefinition to an "AttributeList"
> > * remove link to MSD in MetadataSet
> > * rename Att to Attribute in MetadataSet
> > 
> > Thanks a lot in advance.
> 
> @dosse FYI, we can change ReportStructure to AttributeList, but cannot remove MetadataStructureComponents as it is necessary for the type refinement.

@jgager I see, the DSD looks like this:

```xml
    <structure:DataStructure id="" agencyID="" version="">
       <structure:DataStructureComponents>
          <structure:DimensionList/>
          <structure:AttributeList/>
          <structure:MeasureList/>
       </structure:DataStructureComponents>
    </structure:DataStructure>
```

Thus, I agree, it's ok if the MSD looks like this:

```xml
    <structure:MetadataStructure id="" agencyID="" version="">
       <structure:MetadataStructureComponents>
          <structure:AttributeList/>
       </structure:MetadataStructureComponents>
    </structure:MetadataStructure>
```

Thanks for the clarification.

2021-03-26 08:08 UTC, glennmdt commented on schemas/SDMXMetadataGeneric.xsd
> +						</xs:element>
@agent97 can you confirm is Jens is correct?

2021-03-26 10:41 UTC, sdmx3mdt commented on schemas/SDMXMetadataGeneric.xsd
> +						</xs:element>
Matt agrees - the MetadataStructure reference can be removed.

2021-03-26 10:42 UTC, sdmx3mdt commented on schemas/SDMXMetadataGeneric.xsd
> +						</xs:element>
Fixed in Commit6 by removing MetadataStructure from MetadataSet

2021-03-26 10:57 UTC, sdmx3mdt commented on schemas/SDMXMetadataGeneric.xsd
> +						</xs:element>
A correction is needed to the Information Model and Section 2 DRAFT 0.9 - tracked as https://sdmx3.atlassian.net/browse/BASE-53

2021-03-26 11:02 UTC, stratosn commented on samples/Codelist/codelist - discriminated union.xml
> +		<str:Constraints>
It may be useful to illustrate also the 'removePrefix' property in Constraints. 
FYI it is only included in the IM (section 2) in version 0.8.

2021-03-26 11:02 UTC, stratosn commented on schemas/SDMXMetadataGeneric.xsd
> +						</xs:element>
@dosse , @glennmdt , the idea of having in a Report the link to the MSD was to allow creating a Report without any specific target.

2021-03-26 11:22 UTC, sdmx3mdt commented on samples/Codelist/codelist - discriminated union.xml
> +		<str:Constraints>
@stratosn Thanks for the reminder - this is captured in issue https://github.com/glennmdt/sdmx-ml/issues/16#issue-839595567 for J's attention.

2021-03-26 11:25 UTC, sdmx3mdt commented on schemas/SDMXCommon.xsd
> +				<xs:attribute name="version" type="VersionType" use="optional" default="1.0">
Captured in issue https://github.com/glennmdt/sdmx-ml/issues/27#issue-841731682

2021-03-26 11:26 UTC, sdmx3mdt commented on schemas/SDMXCommon.xsd
> +						<xs:documentation>This version attribute holds a version number in the format of #[.#]+ (see common:VersionType definition for details). If not supplied, the version number is defaulted to 1.0.
Captured in issue https://github.com/glennmdt/sdmx-ml/issues/26#issue-840012515

2021-03-26 11:26 UTC, sdmx3mdt commented on schemas/SDMXCommonReferences.xsd
> +			<xs:pattern value="(0|[1-9]\d*)(\.(0|[1-9]\d*)){2}(\-(([A-Za-z\-]|([A-Za-z\-][A-Za-z0-9\-]+)|([A-Za-z0-9\-]+[A-Za-z\-][A-Za-z0-9\-]*))|(0|[1-9][0-9]*))(\.(([A-Za-z\-]|([A-Za-z\-][A-Za-z0-9\-]+)|([
Captured in issue https://github.com/glennmdt/sdmx-ml/issues/28#issue-841749898

2021-03-26 11:29 UTC, sdmx3mdt commented on schemas/SDMXStructureOrganisation.xsd
> -				</xs:sequence>
Captured in issue https://github.com/glennmdt/sdmx-ml/issues/29#issue-841751787

2021-03-26 11:30 UTC, sdmx3mdt commented on schemas/SDMXStructureOrganisation.xsd
> -				<xs:attribute name="isFinal" type="xs:boolean" use="optional" fixed="false"/>
Captured in issue https://github.com/glennmdt/sdmx-ml/issues/30#issue-841754676

2021-03-26 11:30 UTC, sdmx3mdt commented on schemas/SDMXStructureOrganisation.xsd
> -				<xs:attribute name="isFinal" type="xs:boolean" use="optional" fixed="false"/>
Captured in issue https://github.com/glennmdt/sdmx-ml/issues/30#issue-841754676

2021-03-26 11:30 UTC, sdmx3mdt commented on schemas/SDMXStructureOrganisation.xsd
> -				<xs:attribute name="isFinal" type="xs:boolean" use="optional" fixed="false"/>
Captured in issue https://github.com/glennmdt/sdmx-ml/issues/30#issue-841754676

2021-03-26 11:31 UTC, sdmx3mdt commented on schemas/SDMXStructureOrganisation.xsd
> +				<xs:attribute name="version" type="common:VersionType" use="optional" fixed="1.0"/>
Captured in issue https://github.com/glennmdt/sdmx-ml/issues/30#issue-841754676

2021-03-26 11:39 UTC, sdmx3mdt commented on schemas/SDMXMetadataGeneric.xsd
> +	<xs:element name="Att" type="AttributeType">
Fixed in Commit6 by changing "Att" to "Attribute"

2021-03-26 12:21 UTC, sdmx3mdt commented on schemas/SDMXStructureMetadataStructure.xsd
> +					<xs:element ref="ReportStructure"/>
Captured in issue https://github.com/glennmdt/sdmx-ml/issues/15#issue-839585455

2021-04-16 15:23 UTC, sdmx3mdt commented on schemas/SDMXStructureOrganisation.xsd
> -				</xs:sequence>
Fixed in ticket https://github.com/glennmdt/sdmx-ml/issues/29#issue-841751787

2021-04-16 15:23 UTC, sdmx3mdt commented on schemas/SDMXStructureOrganisation.xsd
> -				<xs:attribute name="isFinal" type="xs:boolean" use="optional" fixed="false"/>
Fixed in ticket https://github.com/glennmdt/sdmx-ml/issues/30#issue-841754676

2021-04-16 15:24 UTC, sdmx3mdt commented on samples/Codelist/codelist - discriminated union.xml
> +		<str:Constraints>
Fixed in ticket

2021-04-16 15:26 UTC, sdmx3mdt commented on schemas/SDMXStructureOrganisation.xsd
> +				<xs:attribute name="version" type="common:VersionType" use="optional" fixed="1.0"/>
Fixed in ticket https://github.com/glennmdt/sdmx-ml/issues/30#issue-841754676

2021-04-16 15:26 UTC, sdmx3mdt commented on schemas/SDMXStructureOrganisation.xsd
> -				<xs:attribute name="isFinal" type="xs:boolean" use="optional" fixed="false"/>
Fixed in ticket https://github.com/glennmdt/sdmx-ml/issues/30#issue-841754676

2021-04-16 15:30 UTC, sdmx3mdt commented on schemas/SDMXMetadataGeneric.xsd
> +						</xs:element>
@stratosn has the correction you proposed to the information model been made concerning Metadatasets referencing MSDs?

2021-04-16 15:31 UTC, sdmx3mdt commented on schemas/SDMXStructureMetadataStructure.xsd
> +					<xs:element ref="ReportStructure"/>
Fixed in ticket https://github.com/glennmdt/sdmx-ml/issues/15#issue-839585455

2021-04-16 15:32 UTC, sdmx3mdt commented on schemas/SDMXCommon.xsd
> +				<xs:attribute name="version" type="VersionType" use="optional" default="1.0">
Fixed in ticket https://github.com/glennmdt/sdmx-ml/issues/27#issue-841731682

2021-04-16 15:32 UTC, sdmx3mdt commented on schemas/SDMXCommon.xsd
> +						<xs:documentation>This version attribute holds a version number in the format of #[.#]+ (see common:VersionType definition for details). If not supplied, the version number is defaulted to 1.0.
Fixed in ticket https://github.com/glennmdt/sdmx-ml/issues/26#issue-840012515

2021-04-16 15:32 UTC, sdmx3mdt commented on schemas/SDMXStructureOrganisation.xsd
> -				</xs:sequence>
Fixed in ticket https://github.com/glennmdt/sdmx-ml/issues/29#issue-841751787

2021-04-16 15:33 UTC, sdmx3mdt commented on schemas/SDMXStructureOrganisation.xsd
> -				<xs:attribute name="isFinal" type="xs:boolean" use="optional" fixed="false"/>
Fixed in ticket https://github.com/glennmdt/sdmx-ml/issues/30#issue-841754676

2021-04-16 15:33 UTC, sdmx3mdt commented on schemas/SDMXStructureOrganisation.xsd
> -				<xs:attribute name="isFinal" type="xs:boolean" use="optional" fixed="false"/>
Fixed in ticket https://github.com/glennmdt/sdmx-ml/issues/30#issue-841754676

2021-04-16 15:34 UTC, sdmx3mdt commented on schemas/SDMXStructureOrganisation.xsd
> -				<xs:attribute name="isFinal" type="xs:boolean" use="optional" fixed="false"/>
Fixed in ticket https://github.com/glennmdt/sdmx-ml/issues/30#issue-841754676

2021-04-16 15:35 UTC, sdmx3mdt commented on schemas/SDMXStructureOrganisation.xsd
> +				<xs:attribute name="version" type="common:VersionType" use="optional" fixed="1.0"/>
Fixed in ticket https://github.com/glennmdt/sdmx-ml/issues/30#issue-841754676

2021-04-16 15:43 UTC, sdmx3mdt commented on schemas/SDMXMetadataGeneric.xsd
> +						</xs:element>
XML schema fixed in ticket https://github.com/glennmdt/sdmx-ml/issues/13

2021-04-16 19:38 UTC, stratosn commented on schemas/SDMXMetadataGeneric.xsd
> +						</xs:element>
@sdmx3mdt yes, it is already in place.

2021-05-04 18:42 UTC, dosse approved these changes, later dismissed

2021-05-04 18:42 UTC, dosse commented on schemas/SDMXStructure.xsd
> +				<xs:unique name="UniqueMetaataProviderScheme">
Typo

2021-05-04 18:42 UTC, dosse commented on schemas/SDMXStructure.xsd
> +	<xs:complexType name="StructureMappingsType">
Why not simply "StructureMaps" or "Maps" instead of "StructureMappings"? It is confusing that the containers change names compared to their content.
It should be "CustomTypeSchemes" instead of "CustomTypes", etc.
This also concerns "Concepts" that should be better "ConceptSchemes".

2021-05-04 18:42 UTC, dosse commented on schemas/SDMXStructure.xsd
>  		<xs:annotation>
"Constraints" should be separate "DataConstraints" and "MetadataConstraints". Why this unnecessary complexity of changing container names compared to their content?

2021-05-04 18:42 UTC, dosse commented on schemas/SDMXStructure.xsd
> +			<xs:element name="MetadataProvisionAgreement" type="MetadataProvisionAgreementType">
There should be a separate "MetadataProvisionAgreements" container. Why this unnecessary complexity of changing container names compared to their content?

2021-05-04 18:48 UTC, dosse commented on schemas/SDMXStructure.xsd
> +				<xs:unique name="UniqueMetaataProviderScheme">
@sdmx3mdt  @jgager  The typo is still there.

2021-05-04 18:50 UTC, dosse commented on schemas/SDMXStructure.xsd
> +	<xs:complexType name="StructureMappingsType">
@sdmx3mdt @jgager Still not addressed. A coherent and logical wording is very important for an easily understandable standard.

2021-05-04 18:58 UTC, dosse commented
@sdmx3mdt @jgager
"This branch has conflicts that must be resolved.
 Use the command line to resolve conflicts before continuing."
Conflicting files
README.rst

But I do not have the command line tool...

2021-05-05 15:34 UTC, sdmx3mdt commented on schemas/SDMXStructure.xsd
> +				<xs:unique name="UniqueMetaataProviderScheme">
Captured in ticket https://github.com/glennmdt/sdmx-ml/issues/39

2021-05-05 15:37 UTC, sdmx3mdt commented on schemas/SDMXStructure.xsd
> +	<xs:complexType name="StructureMappingsType">
Captured in ticket https://github.com/glennmdt/sdmx-ml/issues/40

2021-05-05 15:41 UTC, dosse commented on schemas/SDMXStructure.xsd
> +				<xs:unique name="UniqueMetaataProviderScheme">
ok

2021-05-05 15:41 UTC, dosse commented on schemas/SDMXStructure.xsd
> +	<xs:complexType name="StructureMappingsType">
ok

2021-05-05 15:41 UTC, dosse approved these changes

2021-05-05 15:42 UTC, merged